import { Project, Sponsor, VolunteerApplication, GalleryMedia, BeneficiaryStory, CMSContent, AuditLog, AppNotification, NeedItem, User, HeroConfig, ImpactHubConfig, ImpactTimelineEvent, LiveActivityItem, FoundationScorecard, FoundationHealthData, FoundationAnalyticsData, CommunityLevel, Badge, PointRule, UserReputation, ProjectFeedback, AnnualCommunityAward, CorporateAccount, SponsorshipPackage, CorporateReport } from '../types.js';

export const initialImpactHubConfig: ImpactHubConfig = {
  refreshIntervalSeconds: 10,
  featuredProjectId: 'proj-1', // Default featured project ID
  publicStatsEnabled: true,
  healthScorePublic: true,
  widgetsOrder: [
    'pinned_announcement',
    'live_metrics',
    'featured_project',
    'impact_map',
    'timeline',
    'activity_feed',
    'scorecard',
    'success_stories',
    'health_indicator',
  ],
  pinnedAnnouncement: {
    id: 'ann-1',
    title: 'Annual Foundation Impact Summit & Trans-Audited Report Release',
    message: 'Join us live on September 15 for the 2026 Caribbean Community Impact Briefing. All financial ledgers and field audit logs are open for public download.',
    date: '2026-08-01',
    type: 'event',
    link: 'https://vision79.org/summit',
    active: true,
  },
  metricsConfig: [
    { id: 'communities_served', label: 'Communities Served', value: 14, prefix: '', suffix: ' Districts', enabled: true, order: 1, category: 'community' },
    { id: 'lives_impacted', label: 'Lives Impacted', value: 18400, prefix: '', suffix: '+', enabled: true, order: 2, category: 'community' },
    { id: 'active_projects', label: 'Active Projects', value: 8, prefix: '', suffix: '', enabled: true, order: 3, category: 'projects' },
    { id: 'completed_projects', label: 'Completed Projects', value: 52, prefix: '', suffix: '', enabled: true, order: 4, category: 'projects' },
    { id: 'planning_projects', label: 'Projects in Planning', value: 6, prefix: '', suffix: '', enabled: true, order: 5, category: 'projects' },
    { id: 'proposals', label: 'Community Proposals', value: 29, prefix: '', suffix: '', enabled: true, order: 6, category: 'community' },
    { id: 'votes_cast', label: 'Community Votes Cast', value: 4820, prefix: '', suffix: '', enabled: true, order: 7, category: 'community' },
    { id: 'volunteers_registered', label: 'Volunteers Registered', value: 1840, prefix: '', suffix: '', enabled: true, order: 8, category: 'volunteers' },
    { id: 'volunteer_hours', label: 'Volunteer Hours Logged', value: 14200, prefix: '', suffix: ' hrs', enabled: true, order: 9, category: 'volunteers' },
    { id: 'sponsors', label: 'Active Corporate Sponsors', value: 18, prefix: '', suffix: '', enabled: true, order: 10, category: 'financial' },
    { id: 'donors', label: 'Individual Donors', value: 1250, prefix: '', suffix: '', enabled: true, order: 11, category: 'financial' },
    { id: 'cash_donations', label: 'Cash Donations Received', value: 750000, prefix: 'EC$', suffix: '', enabled: true, order: 12, category: 'financial' },
    { id: 'inkind_donations', label: 'In-Kind Goods Value', value: 185000, prefix: 'EC$', suffix: '', enabled: true, order: 13, category: 'financial' },
    { id: 'funds_this_month', label: 'Funds Raised This Month', value: 68400, prefix: 'EC$', suffix: '', enabled: true, order: 14, category: 'financial' },
    { id: 'lifetime_funds', label: 'Total Lifetime Funds Raised', value: 935000, prefix: 'EC$', suffix: '', enabled: true, order: 15, category: 'financial' },
    { id: 'funding_distributed', label: 'Funding Distributed', value: 890000, prefix: 'EC$', suffix: '', enabled: true, order: 16, category: 'financial' },
    { id: 'trees_planted', label: 'Trees & Mangroves Planted', value: 3400, prefix: '', suffix: '', enabled: true, order: 17, category: 'social_environmental' },
    { id: 'scholarships_awarded', label: 'Scholarships Awarded', value: 85, prefix: '', suffix: '', enabled: true, order: 18, category: 'social_environmental' },
    { id: 'students_trained', label: 'Youth Students Trained', value: 1450, prefix: '', suffix: '', enabled: true, order: 19, category: 'social_environmental' },
    { id: 'families_assisted', label: 'Families Assisted', value: 2100, prefix: '', suffix: '', enabled: true, order: 20, category: 'community' },
    { id: 'emergency_responses', label: 'Emergency Responses', value: 12, prefix: '', suffix: '', enabled: true, order: 21, category: 'community' },
    { id: 'meals_distributed', label: 'Nutritional Meals Shared', value: 24500, prefix: '', suffix: '', enabled: true, order: 22, category: 'social_environmental' },
    { id: 'events_hosted', label: 'Community Events Hosted', value: 74, prefix: '', suffix: '', enabled: true, order: 23, category: 'community' },
  ],
};

export const initialTimelineEvents: ImpactTimelineEvent[] = [
  {
    id: 'tl-1',
    title: 'Soufrière Solar Water Station Commissioned',
    description: 'Fully installed 4 solar-powered filtration pumps providing 3,500 residents with clean drinking water.',
    date: '2026-07-20',
    type: 'project_completed',
    projectId: 'proj-1',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'tl-2',
    title: 'EC$500,000 Lifetime Funding Milestone Achieved',
    description: 'Vision79 Foundation surpassed EC$500,000 in direct trans-audited community grants and field investments.',
    date: '2026-06-15',
    type: 'funding_goal',
  },
  {
    id: 'tl-[#]',
    title: 'Vieux Fort STEM Satellite Learning Center Groundbreaking',
    description: 'Broke ground on state-of-the-art satellite lab bringing high-speed internet and 30 workstation laptops to youth.',
    date: '2026-05-10',
    type: 'project_started',
    projectId: 'proj-2',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'tl-4',
    title: 'Island-Wide Mangrove Restoration Drive',
    description: '250 volunteers planted 1,200 mangrove saplings along the coastal wetlands of Dennery.',
    date: '2026-04-22',
    type: 'volunteer_event',
  },
  {
    id: 'tl-5',
    title: 'Caribbean Transparency & Governance Excellence Award',
    description: 'Vision79 Foundation recognized for setting the regional standard in real-time audited financial disclosures.',
    date: '2026-02-14',
    type: 'award',
  },
];

export const initialLiveActivity: LiveActivityItem[] = [
  {
    id: 'act-1',
    timestamp: '2 mins ago',
    actorName: 'Neil V.',
    actionText: 'donated EC$100 to Youth Basketball Court Renovation',
    type: 'donation',
    amount: 100,
    projectId: 'proj-3',
  },
  {
    id: 'act-2',
    timestamp: '14 mins ago',
    actorName: 'Sarah M.',
    actionText: 'pledged 20 ergonomic school chairs for Gros Islet Primary',
    type: 'pledge',
    projectId: 'proj-2',
  },
  {
    id: 'act-3',
    timestamp: '45 mins ago',
    actorName: 'LUCELEC Caribbean',
    actionText: 'became a Platinum Corporate Sponsor',
    type: 'sponsor',
  },
  {
    id: 'act-4',
    timestamp: '1 hour ago',
    actorName: 'Soufrière Solar Water System',
    actionText: 'reached 100% funding goal!',
    type: 'funding_milestone',
    projectId: 'proj-1',
  },
  {
    id: 'act-5',
    timestamp: '3 hours ago',
    actorName: 'Anonymous Supporter',
    actionText: 'donated EC$250 to Community Garden & Farm Tool Drive',
    type: 'donation',
    isAnonymous: true,
    amount: 250,
  },
  {
    id: 'act-6',
    timestamp: '5 hours ago',
    actorName: 'Marcus T.',
    actionText: 'registered as a Field Emergency Responder Volunteer',
    type: 'volunteer_signup',
  },
];

export const initialScorecard: FoundationScorecard = {
  projectsOnTimePct: 96.4,
  budgetPerformancePct: 98.2,
  volunteerSatisfactionRating: 4.9,
  communitySatisfactionRating: 4.8,
  fundingSuccessRatePct: 92.5,
  proposalApprovalRatePct: 78.0,
  avgProjectDurationDays: 42,
  avgCommunityRating: 4.9,
  trends: [
    { metric: 'Projects On Time', direction: 'up', changePct: 2.4 },
    { metric: 'Budget Precision', direction: 'stable', changePct: 0.5 },
    { metric: 'Volunteer Satisfaction', direction: 'up', changePct: 1.2 },
    { metric: 'Funding Conversion Rate', direction: 'up', changePct: 4.1 },
  ],
};

export const initialHealthData: FoundationHealthData = {
  financialHealthScore: 98,
  volunteerCapacityScore: 92,
  projectCompletionScore: 96,
  fundingPipelineScore: 89,
  sponsorEngagementScore: 94,
  communityParticipationScore: 95,
  overallHealthScore: 94,
  publicVisibility: true,
};

export const initialAnalyticsData: FoundationAnalyticsData = {
  homepageViews: 34200,
  mostViewedProjects: [
    { projectId: 'proj-1', title: 'Soufrière Solar Water System', views: 8920 },
    { projectId: 'proj-2', title: 'STEM Satellite Lab Gros Islet', views: 6410 },
    { projectId: 'proj-3', title: 'Castries Youth Basketball Court', views: 4230 },
  ],
  donationConversionRate: 8.4,
  volunteerConversionRate: 12.1,
  proposalSubmissionsThisMonth: 14,
  votingParticipationCount: 4820,
  returningVisitorsPct: 64.5,
  sponsorEngagementRate: 91.0,
  monthlyDonationTrend: [
    { month: 'Jan', amount: 42000 },
    { month: 'Feb', amount: 51000 },
    { month: 'Mar', amount: 68000 },
    { month: 'Apr', amount: 59000 },
    { month: 'May', amount: 74000 },
    { month: 'Jun', amount: 82000 },
    { month: 'Jul', amount: 68400 },
  ],
};


export const initialHeroConfig: HeroConfig = {
  activeSlideId: 'hero-slide-1',
  autoRotate: false,
  rotateIntervalSeconds: 8,
  reducedMotion: false,
  slides: [
    {
      id: 'hero-slide-1',
      title: 'Main Foundation Mission',
      headline: 'Empowering Communities Through Direct Action & Radical Transparency.',
      subheading: 'Vision79 Foundation bridges resources and field execution across Saint Lucia with itemized audits, real-time needs boards, and local community leadership.',
      missionStatement: 'Transforming lives through clean water, healthcare infrastructure, and sustainable educational centers across Saint Lucia & Caribbean communities.',
      mediaType: 'video',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waterfall-in-forest-2213-large.mp4',
      imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1920&q=80',
      posterImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1920&q=80',
      fallbackImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1920&q=80',
      primaryCtaText: 'Make a Donation',
      primaryCtaAction: 'donate',
      secondaryCtaText: 'View Audit Ledger',
      secondaryCtaAction: 'transparency',
      overlayOpacity: 70,
      overlayGradient: 'brand',
      stats: [
        { label: 'Funds Raised', value: 750000, prefix: 'EC$' },
        { label: 'Projects Completed', value: 52 },
        { label: 'Active Volunteers', value: 1800 },
        { label: 'Lives Impacted', value: 8400 },
      ],
      enabled: true,
      campaignType: 'standard',
      seoHeading: 'Vision79 Foundation | Direct Action & Radical Transparency in Saint Lucia',
      seoMetaDescription: 'Official website of Vision79 Foundation. Track community projects, itemized supply requests, and audited financial statements in real-time.',
      socialShareImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=630',
    },
    {
      id: 'hero-slide-2',
      title: 'Emergency Appeal - Soufrière Clean Water',
      headline: 'Emergency Appeal: Solar Water Systems for Soufrière Community.',
      subheading: 'Rapid response unit installing 4 solar water purification plants to supply 3,500 residents with safe drinking water.',
      missionStatement: 'Direct field intervention providing sustainable filtration and renewable energy water pumps.',
      mediaType: 'image',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=1920&q=80',
      posterImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=1920&q=80',
      fallbackImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=1920&q=80',
      primaryCtaText: 'Support Clean Water',
      primaryCtaAction: 'projects',
      secondaryCtaText: 'Become a Volunteer',
      secondaryCtaAction: 'volunteer',
      overlayOpacity: 65,
      overlayGradient: 'dark',
      stats: [
        { label: 'Target Goal', value: 45000, prefix: '$' },
        { label: 'Beneficiaries', value: 3500 },
        { label: 'Days Left', value: 14 },
      ],
      enabled: true,
      campaignType: 'emergency',
      seoHeading: 'Soufrière Emergency Water Appeal | Vision79 Foundation',
      seoMetaDescription: 'Support urgent solar water system installation in Soufrière.',
    },
    {
      id: 'hero-slide-3',
      title: 'STEM Satellite Labs 2026',
      headline: 'Investing in Saint Lucia’s Youth Innovators & STEM Centers.',
      subheading: 'Equipping 8 community primary schools with solar satellite internet and modern learning workstations.',
      missionStatement: 'Nurturing future Caribbean leaders through hands-on technology and educational grants.',
      mediaType: 'image',
      imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1920&q=80',
      posterImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1920&q=80',
      primaryCtaText: 'Sponsor a Student',
      primaryCtaAction: 'donate',
      secondaryCtaText: 'Suggest a Project',
      secondaryCtaAction: 'suggest',
      overlayOpacity: 75,
      overlayGradient: 'radial',
      stats: [
        { label: 'Schools Reached', value: 8 },
        { label: 'Laptops Deployed', value: 120 },
        { label: 'Students Enrolled', value: 1450 },
      ],
      enabled: true,
      campaignType: 'seasonal',
      eventCountdownDate: '2026-09-01T00:00:00.000Z',
      seoHeading: 'STEM Satellite Labs Campaign 2026 | Vision79 Foundation',
      seoMetaDescription: 'Join our educational mission to build satellite learning centers.',
    }
  ]
};


export const initialUsers: User[] = [
  {
    id: 'usr_admin',
    name: 'Sarah Vision Director',
    email: 'admin@vision79.org',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    verified: true,
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr_vol1',
    name: 'David Chen',
    email: 'david.chen@gmail.com',
    role: 'volunteer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    skills: ['IT & Tech', 'Teaching', 'Solar Engineering'],
    volunteerHours: 42,
    badges: ['Community Hero', '50 Hours Milestone', 'Tech Mentor'],
    verified: true,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'usr_spon1',
    name: 'Amina Mansour',
    email: 'corp@techforgood.io',
    role: 'sponsor',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    verified: true,
    createdAt: '2025-01-20T12:00:00Z',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj_cleanwater',
    title: 'Clean Water Wells for Sunu District',
    slug: 'clean-water-sunu',
    summary: 'Installing 12 solar-powered deep boreholes to provide safe drinking water to over 8,500 villagers in Sunu District.',
    description: `Access to clean, safe drinking water remains a vital challenge for families in the rural Sunu District. Currently, women and children walk over 6 kilometers daily to fetch untreated river water, leading to frequent waterborne illness and missed school days.

Vision79 Foundation is drilling 12 solar-powered deep boreholes complete with 10,000-liter storage tanks and filtration systems. Community water committees are being trained for maintenance, ensuring long-term sustainability.`,
    category: 'Water & Sanitation',
    tags: ['Clean Water', 'Solar Energy', 'Community Health', 'Rural Care'],
    location: {
      city: 'Sunu Valley',
      region: 'Western District',
      lat: 6.87,
      lng: -11.23,
    },
    coverImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1594708767771-a7502209ff51?auto=format&fit=crop&w=800&q=80',
    ],
    documents: [
      { name: 'Hydrological Assessment Report.pdf', url: '#', size: '2.4 MB' },
      { name: 'Community Water Committee Charter.pdf', url: '#', size: '1.1 MB' },
    ],
    targetAmount: 45000,
    raisedAmount: 32400,
    status: 'Active',
    startDate: '2025-03-01',
    endDate: '2025-11-30',
    team: [
      { name: 'Eng. Marcus Vance', role: 'Project Director', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
      { name: 'Grace Kalu', role: 'Community Liaison', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80' },
    ],
    needs: [
      {
        id: 'need_cw1',
        projectId: 'proj_cleanwater',
        projectName: 'Clean Water Wells for Sunu District',
        title: 'Deep Borehole Solar Water Pump Sets',
        category: 'Equipment',
        quantityNeeded: 12,
        quantityPledged: 9,
        quantityReceived: 7,
        unit: 'sets',
        estimatedCostPerUnit: 1800,
        urgency: 'High',
      },
      {
        id: 'need_cw2',
        projectId: 'proj_cleanwater',
        projectName: 'Clean Water Wells for Sunu District',
        title: '10,000L Overhead Poly Water Tanks',
        category: 'Materials',
        quantityNeeded: 12,
        quantityPledged: 12,
        quantityReceived: 10,
        unit: 'tanks',
        estimatedCostPerUnit: 950,
        urgency: 'Medium',
      },
      {
        id: 'need_cw3',
        projectId: 'proj_cleanwater',
        projectName: 'Clean Water Wells for Sunu District',
        title: 'Community Water Testing & Chlorination Kits',
        category: 'Supplies',
        quantityNeeded: 25,
        quantityPledged: 15,
        quantityReceived: 12,
        unit: 'kits',
        estimatedCostPerUnit: 120,
        urgency: 'High',
      },
    ],
    milestones: [
      { id: 'm_1', title: 'Hydro-Geological Surveying', description: 'Survey and mapping of 12 high-yield aquifer sites', targetDate: '2025-03-15', completedDate: '2025-03-20', status: 'Completed' },
      { id: 'm_2', title: 'Drilling & Well Casing', description: 'Drilling boreholes to 80-meter depth with PVC casing', targetDate: '2025-05-30', completedDate: '2025-06-10', status: 'Completed' },
      { id: 'm_3', title: 'Solar Array & Pump Installation', description: 'Mounting solar panels, submersible pumps, and piping', targetDate: '2025-08-30', status: 'In Progress' },
      { id: 'm_4', title: 'Water Quality Certification', description: 'Testing water samples against WHO drinking standards', targetDate: '2025-10-15', status: 'Planned' },
      { id: 'm_5', title: 'Community Handover & Maintenance Workshop', description: 'Training local committee technicians and ribbon cutting', targetDate: '2025-11-30', status: 'Planned' },
    ],
    expenses: [
      { id: 'exp_1', projectId: 'proj_cleanwater', category: 'Surveying & Permits', description: 'Geophysical survey & EPA drilling permits', approvedBudget: 3500, actualSpent: 3400, vendor: 'HydroGeo Solutions Ltd', date: '2025-03-18', status: 'Approved' },
      { id: 'exp_2', projectId: 'proj_cleanwater', category: 'Drilling & Labor', description: 'Borehole excavation for first 6 sites', approvedBudget: 14000, actualSpent: 13850, vendor: 'DeepRock Engineering', date: '2025-05-25', status: 'Approved' },
      { id: 'exp_3', projectId: 'proj_cleanwater', category: 'Equipment Procurement', description: 'Solar submersible pumps and controllers', approvedBudget: 12000, actualSpent: 11500, vendor: 'SolarPump Global', date: '2025-07-02', status: 'Approved' },
    ],
    updates: [
      {
        id: 'upd_cw1',
        projectId: 'proj_cleanwater',
        authorName: 'Eng. Marcus Vance',
        authorRole: 'Project Director',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        title: 'Borehole #6 Successfully Reached Water Aquifer at 75 Meters!',
        content: 'Huge progress today! Our drilling team tapped into a high-capacity freshwater aquifer in Sunu East village. Flow rate tests exceed 4,200 liters/hour with exceptional clarity. Community elders joined us on site to celebrate!',
        mediaUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80'],
        date: '2025-07-14T14:30:00Z',
        isPinned: true,
        likesCount: 48,
        comments: [
          { id: 'c_1', userName: 'Amina Mansour', userRole: 'Sponsor', userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80', content: 'Incredible milestone! TechForGood is proud to support this installation.', date: '2025-07-14T15:10:00Z' },
          { id: 'c_2', userName: 'David Chen', userRole: 'Volunteer', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', content: 'Can not wait to join the solar installation team next month!', date: '2025-07-14T16:05:00Z' },
        ],
      },
    ],
    beneficiariesCount: 8500,
    impactSummary: 'Eliminating waterborne illnesses for 8,500 villagers and saving 45,000 school hours annually previously lost to fetching water.',
    featured: true,
    followersCount: 312,
  },
  {
    id: 'proj_digitallearning',
    title: 'FutureTech Digital Literacy Labs in 5 Schools',
    slug: 'futuretech-digital-labs',
    summary: 'Outfitting 5 rural schools with 150 solar-powered laptops, starlink satellite internet, and coding curricula for 2,400 students.',
    description: `Rural schools often lack access to modern computer hardware and connectivity, leaving thousands of bright students without digital skills essential for higher education and future career opportunities.

Vision79 Foundation is building 5 fully equipped digital learning labs powered by off-grid solar arrays and satellite internet. We train teachers on digital pedagogy and partner with volunteer coders for weekend workshops.`,
    category: 'Education',
    tags: ['Digital Skills', 'Laptops', 'Schools', 'STEM Education', 'Solar'],
    location: {
      city: 'Kasa District',
      region: 'Central Province',
      lat: 6.95,
      lng: -11.10,
    },
    coverImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    ],
    documents: [
      { name: 'Digital Curriculum Syllabus 2025.pdf', url: '#', size: '3.8 MB' },
    ],
    targetAmount: 38000,
    raisedAmount: 38000,
    status: 'Completed',
    startDate: '2024-09-01',
    endDate: '2025-04-15',
    team: [
      { name: 'Dr. Evelyn Reed', role: 'Education Lead', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80' },
      { name: 'Tariq Johnson', role: 'IT Infrastructure Tech', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80' },
    ],
    needs: [
      {
        id: 'need_dl1',
        projectId: 'proj_digitallearning',
        projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
        title: 'Rugged Educational Laptops',
        category: 'Electronics',
        quantityNeeded: 150,
        quantityPledged: 150,
        quantityReceived: 150,
        unit: 'laptops',
        estimatedCostPerUnit: 220,
        urgency: 'Critical',
      },
      {
        id: 'need_dl2',
        projectId: 'proj_digitallearning',
        projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
        title: 'Interactive Smart Boards & Projectors',
        category: 'Equipment',
        quantityNeeded: 5,
        quantityPledged: 5,
        quantityReceived: 5,
        unit: 'units',
        estimatedCostPerUnit: 800,
        urgency: 'High',
      },
    ],
    milestones: [
      { id: 'm_dl1', title: 'School Site Surveys & Power Readiness', description: 'Checking electrical wiring and solar roofs across 5 schools', targetDate: '2024-09-20', completedDate: '2024-09-22', status: 'Completed' },
      { id: 'm_dl2', title: 'Hardware Procurement & Setup', description: 'Custom laptop imaging with offline educational software', targetDate: '2024-11-15', completedDate: '2024-11-28', status: 'Completed' },
      { id: 'm_dl3', title: 'Teacher Digital Certification', description: 'Training 24 teachers on digital curriculum delivery', targetDate: '2025-02-10', completedDate: '2025-02-18', status: 'Completed' },
      { id: 'm_dl4', title: 'Grand Opening & Student Launch', description: 'First official coding class launched across all 5 schools', targetDate: '2025-04-15', completedDate: '2025-04-15', status: 'Completed' },
    ],
    expenses: [
      { id: 'exp_dl1', projectId: 'proj_digitallearning', category: 'Hardware Procurement', description: '150 rugged laptops & security lockers', approvedBudget: 31000, actualSpent: 30800, vendor: 'EduTech Hardware Direct', date: '2024-10-10', status: 'Approved' },
      { id: 'exp_dl2', projectId: 'proj_digitallearning', category: 'Connectivity & Solar', description: '5 Satellite Internet Kits + Roof Solar Arrays', approvedBudget: 5500, actualSpent: 5420, vendor: 'OrbitNet Solar', date: '2024-11-05', status: 'Approved' },
    ],
    updates: [
      {
        id: 'upd_dl1',
        projectId: 'proj_digitallearning',
        authorName: 'Dr. Evelyn Reed',
        authorRole: 'Education Lead',
        authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        title: '2,400 Students Now Enrolled in Weekly Scratch & Python Classes!',
        content: 'We are thrilled to share that all 5 computer labs are operating at full capacity! Over 2,400 elementary and high school students are now writing their first lines of code and exploring interactive science simulations every single week.',
        mediaUrls: ['https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80'],
        date: '2025-05-02T10:00:00Z',
        isPinned: true,
        likesCount: 92,
        comments: [],
      },
    ],
    beneficiariesCount: 2400,
    impactSummary: '100% of students in 5 target schools passed their national ICT exams with high honors.',
    featured: true,
    followersCount: 540,
  },
  {
    id: 'proj_maternalclinic',
    title: 'Maternal & Child Health Care Mobile Clinic',
    slug: 'maternal-mobile-clinic',
    summary: 'Deploying a custom medical van outfitted with ultrasound, diagnostics, and trained midwives to reach remote mountain villages.',
    description: `High maternal mortality in remote highland communities is primarily caused by delays in reaching healthcare facilities.

Our Mobile Health Clinic visits 18 isolated mountain villages every fortnight, providing free prenatal checkups, emergency ultrasound scans, vaccinations, and safe delivery kits.`,
    category: 'Healthcare',
    tags: ['Maternal Health', 'Mobile Clinic', 'Vaccinations', 'Highland Care'],
    location: {
      city: 'Highland Ridge',
      region: 'North Province',
      lat: 7.12,
      lng: -11.45,
    },
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    ],
    documents: [],
    targetAmount: 62000,
    raisedAmount: 41500,
    status: 'Active',
    startDate: '2025-01-10',
    endDate: '2025-12-31',
    team: [
      { name: 'Dr. Maya Lin', role: 'Medical Director', avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80' },
    ],
    needs: [
      {
        id: 'need_m1',
        projectId: 'proj_maternalclinic',
        projectName: 'Maternal & Child Health Care Mobile Clinic',
        title: 'Portable Diagnostic Ultrasound Scanners',
        category: 'Medical Devices',
        quantityNeeded: 3,
        quantityPledged: 2,
        quantityReceived: 2,
        unit: 'scanners',
        estimatedCostPerUnit: 3500,
        urgency: 'Critical',
      },
      {
        id: 'need_m2',
        projectId: 'proj_maternalclinic',
        projectName: 'Maternal & Child Health Care Mobile Clinic',
        title: 'Sterile Delivery Kits & Neonatal Care Supplies',
        category: 'Medical Supplies',
        quantityNeeded: 500,
        quantityPledged: 350,
        quantityReceived: 300,
        unit: 'kits',
        estimatedCostPerUnit: 25,
        urgency: 'High',
      },
    ],
    milestones: [
      { id: 'm_mc1', title: 'Custom Medical Van Fabrication', description: 'Outfitting heavy-duty 4x4 van with examination table & cold chain fridge', targetDate: '2025-02-28', completedDate: '2025-03-10', status: 'Completed' },
      { id: 'm_mc2', title: 'Staffing & Mobile Midwife Training', description: 'Recruiting 4 licensed nurse-midwives and driver paramedic', targetDate: '2025-04-15', completedDate: '2025-04-20', status: 'Completed' },
      { id: 'm_mc3', title: 'Fortnightly Route Execution', description: 'Visiting all 18 villages on fixed calendar schedule', targetDate: '2025-12-31', status: 'In Progress' },
    ],
    expenses: [
      { id: 'exp_mc1', projectId: 'proj_maternalclinic', category: 'Vehicle & Modification', description: '4x4 Ambulance conversion & solar power', approvedBudget: 38000, actualSpent: 37500, vendor: 'MedVan Specialist Engineering', date: '2025-02-15', status: 'Approved' },
    ],
    updates: [
      {
        id: 'upd_mc1',
        projectId: 'proj_maternalclinic',
        authorName: 'Dr. Maya Lin',
        authorRole: 'Medical Director',
        authorAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80',
        title: 'Over 600 Prenatal Scans Delivered Across 18 Villages!',
        content: 'Our mobile team completed its 100th village patrol this week. Early diagnostic scans allowed our midwives to identify 14 high-risk pregnancies and coordinate safe hospital transfers before emergency complications arose.',
        mediaUrls: ['https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80'],
        date: '2025-06-20T11:15:00Z',
        likesCount: 65,
        comments: [],
      },
    ],
    beneficiariesCount: 4200,
    impactSummary: 'Zero maternal deaths reported in partner villages since mobile clinic rollout.',
    featured: true,
    followersCount: 280,
  },
];

export const initialSponsors: Sponsor[] = [
  {
    id: 'spon_1',
    name: 'TechForGood Global Corporation',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    website: 'https://techforgood.example.org',
    tier: 'Platinum',
    totalContributed: 55000,
    sponsoredProjectIds: ['proj_cleanwater', 'proj_digitallearning'],
    joinedDate: '2024-06-01',
    taxReceiptsCount: 4,
  },
  {
    id: 'spon_2',
    name: 'Apex Renewable Energy Ltd',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=300&q=80',
    website: 'https://apexenergy.example.com',
    tier: 'Gold',
    totalContributed: 28000,
    sponsoredProjectIds: ['proj_cleanwater'],
    joinedDate: '2024-11-12',
    taxReceiptsCount: 2,
  },
  {
    id: 'spon_3',
    name: 'Horizon Healthcare Fund',
    logo: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=300&q=80',
    website: 'https://horizonhealth.example.org',
    tier: 'Silver',
    totalContributed: 12500,
    sponsoredProjectIds: ['proj_maternalclinic'],
    joinedDate: '2025-01-05',
    taxReceiptsCount: 1,
  },
];

export const initialDonations = [
  {
    id: 'don_1',
    projectId: 'proj_cleanwater',
    projectName: 'Clean Water Wells for Sunu District',
    donorName: 'Amina Mansour',
    donorEmail: 'corp@techforgood.io',
    amount: 10000,
    type: 'Corporate' as const,
    isAnonymous: false,
    date: '2025-03-05T14:20:00Z',
    receiptNumber: 'REC-2025-00104',
    status: 'Completed' as const,
  },
  {
    id: 'don_2',
    projectId: 'proj_cleanwater',
    projectName: 'Clean Water Wells for Sunu District',
    donorName: 'Anonymous Community Member',
    donorEmail: 'donor@hidden.org',
    amount: 500,
    type: 'Cash' as const,
    isAnonymous: true,
    date: '2025-04-12T09:10:00Z',
    receiptNumber: 'REC-2025-00122',
    status: 'Completed' as const,
  },
  {
    id: 'don_3',
    projectId: 'proj_digitallearning',
    projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
    donorName: 'David Chen',
    donorEmail: 'david.chen@gmail.com',
    amount: 250,
    type: 'Recurring' as const,
    recurringFrequency: 'monthly' as const,
    isAnonymous: false,
    date: '2025-05-01T10:00:00Z',
    receiptNumber: 'REC-2025-00189',
    status: 'Completed' as const,
  },
];

export const initialVolunteers: VolunteerApplication[] = [
  {
    id: 'vol_app1',
    userId: 'usr_vol1',
    userName: 'David Chen',
    userEmail: 'david.chen@gmail.com',
    projectId: 'proj_cleanwater',
    projectName: 'Clean Water Wells for Sunu District',
    skills: ['Solar Engineering', 'Electrical Maintenance', 'Community Teaching'],
    availability: 'Saturdays & Sundays (10 hours/week)',
    emergencyContact: { name: 'Elena Chen', phone: '+1 555 019 2831', relation: 'Sister' },
    status: 'Approved',
    appliedDate: '2025-02-10',
    loggedHours: 42,
    attendanceQrToken: 'QR-VOL-DAVID-CHEN-2025',
  },
  {
    id: 'vol_app2',
    userId: 'usr_vol2',
    userName: 'Maria Santos',
    userEmail: 'maria.s@example.org',
    projectId: 'proj_maternalclinic',
    projectName: 'Maternal & Child Health Care Mobile Clinic',
    skills: ['First Aid', 'Patient Logistics', 'Translation'],
    availability: 'Weekdays afternoons',
    emergencyContact: { name: 'Juan Santos', phone: '+1 555 018 9910', relation: 'Spouse' },
    status: 'Pending',
    appliedDate: '2025-07-01',
    loggedHours: 0,
    attendanceQrToken: 'QR-VOL-MARIA-SANTOS-2025',
  },
];

export const initialGallery: GalleryMedia[] = [
  {
    id: 'gal_1',
    projectId: 'proj_cleanwater',
    projectName: 'Clean Water Wells for Sunu District',
    title: 'Sunu East Borehole Drilling Site Before & After',
    caption: 'Transformation from muddy untreated riverbed water source to clean solar-powered borehole tapstand.',
    type: 'before_after',
    url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1000&q=80',
    beforeUrl: 'https://images.unsplash.com/photo-1594708767771-a7502209ff51?auto=format&fit=crop&w=1000&q=80',
    afterUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1000&q=80',
    album: 'Clean Water',
    tags: ['Water', 'Before/After', 'Solar', 'Sunu'],
    date: '2025-06-15',
  },
  {
    id: 'gal_2',
    projectId: 'proj_digitallearning',
    projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
    title: 'Students Writing First Python Script',
    caption: 'Students at Kasa High School testing their interactive game code.',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    album: 'Education & Tech',
    tags: ['Laptops', 'Students', 'Coding'],
    date: '2025-04-18',
  },
  {
    id: 'gal_3',
    projectId: 'proj_maternalclinic',
    projectName: 'Maternal & Child Health Care Mobile Clinic',
    title: 'Mobile Healthcare Patrol in Highland Ridge',
    caption: 'Midwives conducting prenatal health screenings in local village center.',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=80',
    album: 'Healthcare',
    tags: ['Maternal Health', 'Mobile Clinic'],
    date: '2025-05-22',
  },
];

export const initialBeneficiaryStories: BeneficiaryStory[] = [
  {
    id: 'story_1',
    projectId: 'proj_cleanwater',
    projectName: 'Clean Water Wells for Sunu District',
    beneficiaryName: 'Mariama & Her Family',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    quote: 'Before the borehole in our village, my daughters missed two days of school every week carrying water buckets. Now clean water is 2 minutes from our front door!',
    fullStory: `Mariama lives with her four children in Sunu East village. For over 15 years, fetching water required a dangerous 6-kilometer trek down steep ravines to the muddy riverbed.

Thanks to the Vision79 Foundation clean water initiative, a solar borehole was installed right in the village square. Mariama's daughters are now top performers in their school, and waterborne typhus has completely disappeared from their household.`,
    location: 'Sunu East Village',
    date: '2025-06-25',
  },
  {
    id: 'story_2',
    projectId: 'proj_digitallearning',
    projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
    beneficiaryName: 'Emmanuel O.',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    quote: 'I had never touched a real computer before September. Last month, I won second place in the regional youth software challenge!',
    fullStory: `Emmanuel, 16, attends Kasa Public Academy. Before Vision79 Foundation installed the FutureTech Digital Lab, textbook diagrams were his only window into computing.

Through dedicated practice during after-school coding sessions, Emmanuel learned Web development and built an automated rainfall logging tool for local farmers. He dreams of studying Computer Science at university next year.`,
    location: 'Kasa District',
    date: '2025-05-10',
  },
];

export const initialCMSContent: CMSContent = {
  aboutMission: 'Vision79 Foundation is dedicated to empowering rural and underserved communities through sustainable infrastructure, digital education, accessible healthcare, and transparent grassroots impact.',
  aboutVision: 'A world where every community has reliable access to clean water, quality education, essential healthcare, and equal opportunity to thrive.',
  aboutHistory: 'Founded in 2022 by a passionate coalition of engineers, educators, and healthcare professionals, Vision79 Foundation has delivered 28 major community projects across 4 regions, directly improving the lives of over 45,000 people.',
  faqList: [
    { question: 'How much of my donation goes directly to field projects?', answer: '100% of public donations directly fund project execution. Operational and administrative overhead is fully subsidized by our corporate Platinum founding partners.' },
    { question: 'Can I request a tax deductible receipt?', answer: 'Yes! All donations receive an immediate official tax receipt with a unique serial code downloadable in your profile or sent via email.' },
    { question: 'How do I sign up as a volunteer?', answer: 'Visit our Volunteer page, browse open opportunities, select your skills, and submit an application. Our team reviews applications within 48 hours.' },
    { question: 'What is the Needs Board?', answer: 'The Needs Board breaks down every active project into tangible equipment, materials, and supplies (e.g. solar pumps, laptops, medical kits) so donors and partners can pledge exact physical items or funds directly.' },
  ],
  policies: [
    { title: 'Transparency Policy', content: 'Every dollar received is publicly logged on our Transparency Dashboard alongside verified vendor invoices and expense reports.' },
    { title: 'Data Privacy & Security', content: 'We protect user data with end-to-end encryption and strict WCAG AA compliance. We never share donor details with third-party advertisers.' },
    { title: 'Child Protection & Safeguarding', content: 'All volunteers and field staff undergo rigorous background checks and safeguarding training prior to working in school or health environments.' },
  ],
  contactEmail: 'contact@vision79.org',
  contactPhone: '+1 (800) 555-V790',
  contactAddress: '79 Innovation Way, Suite 400, Capital District, V79 2026',
};

export const initialCommunityLevels: CommunityLevel[] = [
  { levelNumber: 1, title: 'Community Member', minPoints: 0, maxPoints: 99, color: '#94A3B8', badgeIcon: 'User' },
  { levelNumber: 2, title: 'Community Supporter', minPoints: 100, maxPoints: 299, color: '#38BDF8', badgeIcon: 'Heart' },
  { levelNumber: 3, title: 'Community Champion', minPoints: 300, maxPoints: 699, color: '#A855F7', badgeIcon: 'Award' },
  { levelNumber: 4, title: 'Community Builder', minPoints: 700, maxPoints: 1499, color: '#F27D26', badgeIcon: 'Zap' },
  { levelNumber: 5, title: 'Foundation Ambassador', minPoints: 1500, maxPoints: 999999, color: '#10B981', badgeIcon: 'Crown' },
];

export const initialBadges: Badge[] = [
  { id: 'b_first_step', name: 'First Step', description: 'Completed first verified contribution.', icon: 'Footprints', category: 'contribution' },
  { id: 'b_community_hero', name: 'Community Hero', description: 'Logged over 100 volunteer service hours in field missions.', icon: 'Shield', category: 'volunteering' },
  { id: 'b_project_champion', name: 'Project Champion', description: 'Actively participated in completing a community project.', icon: 'Trophy', category: 'project' },
  { id: 'b_foundation_builder', name: 'Foundation Builder', description: 'Supported 10 or more verified foundation projects.', icon: 'Building2', category: 'project' },
  { id: 'b_early_supporter', name: 'Early Supporter', description: 'Joined and contributed during Foundation launch phase.', icon: 'Sparkles', category: 'special' },
  { id: 'b_community_organizer', name: 'Community Organizer', description: 'Successfully led or co-organized a community initiative.', icon: 'Users', category: 'engagement' },
  { id: 'b_env_champion', name: 'Environmental Champion', description: 'Supported coastal restoration & clean energy projects.', icon: 'TreePine', category: 'project' },
  { id: 'b_edu_advocate', name: 'Education Advocate', description: 'Supported youth literacy, digital labs & STEM programs.', icon: 'GraduationCap', category: 'project' },
  { id: 'b_sports_partner', name: 'Sports Development Partner', description: 'Supported youth athletic facilities and sports drives.', icon: 'Dumbbell', category: 'project' },
  { id: 'b_order_merit', name: 'Order of Merit', description: 'Highest distinction awarded manually by Foundation Board.', icon: 'Medal', category: 'honour', isManualAward: true },
];

export const initialPointRules: PointRule[] = [
  { id: 'pr_1', actionKey: 'first_donation', actionName: 'First Donation', points: 50, category: 'donation', description: 'Awarded upon making your first verified donation' },
  { id: 'pr_2', actionKey: 'donation_over_100', actionName: 'Donation over EC$100', points: 25, category: 'donation', description: 'Awarded for contributions exceeding EC$100' },
  { id: 'pr_3', actionKey: 'recurring_donation', actionName: 'Recurring Monthly Donation', points: 100, category: 'donation', description: 'Awarded when setting up a monthly pledge' },
  { id: 'pr_4', actionKey: 'major_sponsor', actionName: 'Major Project Sponsor', points: 250, category: 'donation', description: 'Awarded for major corporate or individual sponsorships' },
  { id: 'pr_5', actionKey: 'vol_register', actionName: 'Volunteer Registration', points: 20, category: 'volunteering', description: 'Awarded when completing volunteer profile vetting' },
  { id: 'pr_6', actionKey: 'vol_attendance', actionName: 'Volunteer Event Attendance', points: 50, category: 'volunteering', description: 'Awarded for attending a field volunteer event' },
  { id: 'pr_7', actionKey: 'vol_10_hours', actionName: '10 Volunteer Hours Logged', points: 100, category: 'volunteering', description: 'Awarded every 10 logged volunteer hours' },
  { id: 'pr_8', actionKey: 'vol_100_hours', actionName: '100 Volunteer Hours Logged', points: 500, category: 'volunteering', description: 'Major milestone for 100 volunteer hours' },
  { id: 'pr_9', actionKey: 'submit_proposal', actionName: 'Submit Project Proposal', points: 50, category: 'proposal', description: 'Awarded when submitting a detailed community proposal' },
  { id: 'pr_10', actionKey: 'proposal_approved', actionName: 'Proposal Approved for Voting', points: 100, category: 'proposal', description: 'Awarded when proposal passes feasibility review' },
  { id: 'pr_11', actionKey: 'project_completed', actionName: 'Successful Project Completion', points: 250, category: 'proposal', description: 'Awarded when a proposed project reaches 100% completion' },
  { id: 'pr_12', actionKey: 'helpful_comment', actionName: 'Helpful Community Comment', points: 5, category: 'engagement', description: 'Awarded for constructive field updates and discussions' },
  { id: 'pr_13', actionKey: 'positive_feedback', actionName: 'Positive Community Feedback', points: 10, category: 'engagement', description: 'Awarded when community upvotes your comments or updates' },
  { id: 'pr_14', actionKey: 'inkind_item', actionName: 'Provide Needed Goods (In-Kind)', points: 50, category: 'inkind', description: 'Awarded for fulfilling items on the Needs Board' },
  { id: 'pr_15', actionKey: 'large_equipment', actionName: 'Large Equipment Donation', points: 200, category: 'inkind', description: 'Awarded for donating solar pumps, laptops, or heavy tools' },
];

export const initialUserReputations: UserReputation[] = [
  {
    userId: 'u_neil_v',
    userName: 'Neil .V',
    userEmail: 'neil.v@community.org',
    role: 'donor',
    verified: true,
    score: 845,
    levelNumber: 4,
    levelTitle: 'Community Builder',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    badges: [
      { id: 'b_sports_partner', name: 'Sports Champion', description: 'Supported youth athletic facilities and sports drives.', icon: 'Dumbbell', category: 'project', unlockedAt: '2026-03-12' },
      { id: 'b_foundation_builder', name: 'Community Builder', description: 'Supported 10 or more verified foundation projects.', icon: 'Building2', category: 'project', unlockedAt: '2026-05-18' },
      { id: 'b_early_supporter', name: 'Early Supporter', description: 'Joined and contributed during Foundation launch phase.', icon: 'Sparkles', category: 'special', unlockedAt: '2026-01-10' },
    ],
    trustIndicators: ['Verified Member', 'Community Volunteer', 'Long-Time Contributor', 'Project Contributor'],
    projectsSupportedCount: 12,
    volunteerHours: 64,
    totalDonatedEC: 2450,
    projectsProposedCount: 3,
    completedContributionsCount: 18,
    privacySettings: { leaderboardVisibility: 'public', showDonations: true },
    createdAt: '2026-01-10',
  },
  {
    userId: 'u_sarah_m',
    userName: 'Sarah .M',
    userEmail: 'sarah.m@education.org',
    role: 'volunteer',
    verified: true,
    score: 520,
    levelNumber: 3,
    levelTitle: 'Community Champion',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    badges: [
      { id: 'b_first_step', name: 'First Step', description: 'Completed first verified contribution.', icon: 'Footprints', category: 'contribution', unlockedAt: '2026-02-14' },
      { id: 'b_project_champion', name: 'Project Champion', description: 'Actively participated in completing a community project.', icon: 'Trophy', category: 'project', unlockedAt: '2026-04-20' },
      { id: 'b_edu_advocate', name: 'Education Advocate', description: 'Supported youth literacy, digital labs & STEM programs.', icon: 'GraduationCap', category: 'project', unlockedAt: '2026-06-01' },
    ],
    trustIndicators: ['Verified Member', 'Community Volunteer', 'Project Contributor'],
    projectsSupportedCount: 5,
    volunteerHours: 32,
    totalDonatedEC: 1100,
    projectsProposedCount: 2,
    completedContributionsCount: 9,
    privacySettings: { leaderboardVisibility: 'public', showDonations: true },
    createdAt: '2026-02-01',
  },
  {
    userId: 'u_marcus_k',
    userName: 'Marcus .K',
    userEmail: 'marcus.k@env.org',
    role: 'volunteer',
    verified: true,
    score: 1280,
    levelNumber: 4,
    levelTitle: 'Community Builder',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    badges: [
      { id: 'b_community_hero', name: 'Community Hero', description: 'Logged over 100 volunteer service hours in field missions.', icon: 'Shield', category: 'volunteering', unlockedAt: '2026-05-30' },
      { id: 'b_env_champion', name: 'Environmental Champion', description: 'Supported coastal restoration & clean energy projects.', icon: 'TreePine', category: 'project', unlockedAt: '2026-03-22' },
      { id: 'b_foundation_builder', name: 'Foundation Builder', description: 'Supported 10 or more verified foundation projects.', icon: 'Building2', category: 'project', unlockedAt: '2026-06-12' },
    ],
    trustIndicators: ['Verified Member', 'Long-Time Contributor', 'Community Volunteer', 'Foundation Partner'],
    projectsSupportedCount: 18,
    volunteerHours: 120,
    totalDonatedEC: 4800,
    projectsProposedCount: 4,
    completedContributionsCount: 28,
    privacySettings: { leaderboardVisibility: 'public', showDonations: true },
    createdAt: '2026-01-05',
  },
  {
    userId: 'u_elena_r',
    userName: 'Elena .R',
    userEmail: 'elena.r@globalimpact.org',
    role: 'sponsor',
    verified: true,
    score: 1850,
    levelNumber: 5,
    levelTitle: 'Foundation Ambassador',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    badges: [
      { id: 'b_early_supporter', name: 'Early Supporter', description: 'Joined and contributed during Foundation launch phase.', icon: 'Sparkles', category: 'special', unlockedAt: '2026-01-01' },
      { id: 'b_order_merit', name: 'Order of Merit', description: 'Highest distinction awarded manually by Foundation Board.', icon: 'Medal', category: 'honour', isManualAward: true, unlockedAt: '2026-04-10' },
      { id: 'b_community_organizer', name: 'Community Organizer', description: 'Successfully led or co-organized a community initiative.', icon: 'Users', category: 'engagement', unlockedAt: '2026-05-15' },
    ],
    trustIndicators: ['Verified Member', 'Long-Time Contributor', 'Foundation Partner', 'Community Volunteer'],
    projectsSupportedCount: 24,
    volunteerHours: 180,
    totalDonatedEC: 15200,
    projectsProposedCount: 5,
    completedContributionsCount: 42,
    privacySettings: { leaderboardVisibility: 'public', showDonations: true },
    createdAt: '2026-01-01',
  },
];

export const initialProjectFeedback: ProjectFeedback[] = [
  {
    id: 'fb-1',
    projectId: 'proj-1',
    projectTitle: 'Soufrière Solar Water Station',
    userId: 'u_neil_v',
    userName: 'Neil .V',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    userLevelTitle: 'Community Builder',
    ratings: { impact: 5, communication: 5, transparency: 5, execution: 4, communityBenefit: 5 },
    overallScore: 4.8,
    comment: 'The solar filtration system delivered direct clean water to 3,500 residents. The community transparency dashboard kept us updated on every dollar spent.',
    createdAt: '2026-07-25',
  },
  {
    id: 'fb-2',
    projectId: 'proj-1',
    projectTitle: 'Soufrière Solar Water Station',
    userId: 'u_sarah_m',
    userName: 'Sarah .M',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    userLevelTitle: 'Community Champion',
    ratings: { impact: 5, communication: 4, transparency: 5, execution: 5, communityBenefit: 5 },
    overallScore: 4.8,
    comment: 'Extremely well-executed field project. Local youth volunteers were trained on maintenance, ensuring long-term sustainability.',
    createdAt: '2026-07-28',
  },
];

export const initialAnnualAwards: AnnualCommunityAward[] = [
  {
    id: 'award-2025-1',
    year: 2025,
    category: 'Volunteer of the Year',
    winnerName: 'Elena .R',
    winnerUserId: 'u_elena_r',
    winnerRoleOrOrg: 'Lead Field Coordinator',
    winnerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    description: 'Awarded for logging 180+ volunteer hours across 6 rural infrastructure and mangrove planting field drives.',
    quote: 'Direct community service is the most rewarding investment anyone can make.',
    dateAwarded: '2025-12-15',
  },
  {
    id: 'award-2025-2',
    year: 2025,
    category: 'Community Champion',
    winnerName: 'Marcus .K',
    winnerUserId: 'u_marcus_k',
    winnerRoleOrOrg: 'Grassroots Environmental Advocate',
    winnerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    description: 'Recognized for mobilizing over 250 local youth volunteers for coastal wetland restoration in Dennery.',
    quote: 'When the community owns the solution, the impact lasts for generations.',
    dateAwarded: '2025-12-15',
  },
  {
    id: 'award-2025-3',
    year: 2025,
    category: 'Youth Leader',
    winnerName: 'Neil .V',
    winnerUserId: 'u_neil_v',
    winnerRoleOrOrg: 'Soufrière Youth Athletic League',
    winnerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    description: 'Championed the Soufrière Youth Sports & Recreation Park proposal, securing 1,200 community votes.',
    quote: 'Sports give our youth discipline, health, and a safe space to grow together.',
    dateAwarded: '2025-12-15',
  },
  {
    id: 'award-2025-4',
    year: 2025,
    category: 'Corporate Partner of the Year',
    winnerName: 'St. Lucia Telecom & Tech Alliance',
    winnerRoleOrOrg: 'Platinum Founding Sponsor',
    description: 'Fully subsidized high-speed fiber internet and 30 laptops for the Vieux Fort STEM Satellite Learning Center.',
    dateAwarded: '2025-12-15',
  },
  {
    id: 'award-2025-5',
    year: 2025,
    category: 'Most Impactful Project',
    winnerName: 'Soufrière Clean Solar Water Access Initiative',
    projectTitle: 'Soufrière Solar Water Station',
    description: 'Delivered clean drinking water to 3,500 residents with zero grid electricity cost.',
    dateAwarded: '2025-12-15',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    timestamp: '2025-07-14T14:30:00Z',
    actorEmail: 'admin@vision79.org',
    action: 'PUBLISH_PROJECT_UPDATE',
    target: 'proj_cleanwater',
    details: 'Published update: Borehole #6 Successfully Reached Water Aquifer',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'log_2',
    timestamp: '2025-07-02T11:00:00Z',
    actorEmail: 'admin@vision79.org',
    action: 'APPROVE_EXPENSE',
    target: 'exp_3',
    details: 'Approved budget item $11,500 for Solar Submersible Pumps',
    ipAddress: '192.168.1.45',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif_1',
    title: 'New Project Update Published',
    message: 'Borehole #6 in Sunu District reached water aquifer! Read full update.',
    type: 'project',
    date: '2025-07-14T14:30:00Z',
    read: false,
    link: '/projects/clean-water-sunu',
  },
  {
    id: 'notif_2',
    title: 'Donation Receipt Generated',
    message: 'Your tax-deductible receipt REC-2025-00104 is ready for download.',
    type: 'donation',
    date: '2025-03-05T14:20:00Z',
    read: true,
  },
];

export const initialSponsorshipPackages: SponsorshipPackage[] = [
  {
    id: 'pkg-community',
    tier: 'Community Partner',
    name: 'Community Partner',
    minContribution: 2500,
    contributionRequirements: 'EC$2,500 - EC$4,999 annual contribution or equivalent in-kind goods',
    recognitionBenefits: [
      'Listing on Vision79 Foundation Corporate Partners Web Directory',
      'Digital Community Supporter Badge for company website',
      'Mention in quarterly community newsletter',
    ],
    marketingBenefits: [
      'Permission to use Vision79 Foundation "Community Partner" logo',
      'Social media welcome announcement post',
    ],
    projectAccess: [
      'Invitation to general public project ribbon-cutting ceremonies',
      'Quarterly newsletter project updates',
    ],
    reportingBenefits: [
      'Annual tax-deductible 501(c)(3) contribution receipt',
      'Standard annual impact summary certificate',
    ],
    badgeColor: 'border-blue-500/30 bg-blue-500/10 text-blue-300',
  },
  {
    id: 'pkg-bronze',
    tier: 'Bronze Sponsor',
    name: 'Bronze Sponsor',
    minContribution: 5000,
    contributionRequirements: 'EC$5,000 - EC$14,999 annual funding or high-value equipment grant',
    recognitionBenefits: [
      'Medium logo placement on Corporate Partners Wall',
      'Bronze Supporter commemorative glass plaque',
      'Press release co-branding mention',
    ],
    marketingBenefits: [
      'Company profile in Vision79 Annual Impact Review',
      '2 social media feature posts per year',
    ],
    projectAccess: [
      'Access to field site visit opportunities for company leadership',
      'Direct co-funding option for specific project needs',
    ],
    reportingBenefits: [
      'Semi-annual financial expenditure breakdown',
      'Verified beneficiary headcount metric statements',
    ],
    badgeColor: 'border-amber-700/40 bg-amber-900/20 text-amber-400',
  },
  {
    id: 'pkg-silver',
    tier: 'Silver Sponsor',
    name: 'Silver Sponsor',
    minContribution: 15000,
    contributionRequirements: 'EC$15,000 - EC$49,999 annual pledge or technical services provision',
    recognitionBenefits: [
      'Prominent logo on Homepage & Project Detail pages',
      'Co-branded field signage at sponsored project sites',
      'Custom silver trophy & framed certificate',
    ],
    marketingBenefits: [
      'Dedicated company spotlight story on Vision79 Blog',
      'Co-branded video clip for internal CSR communications',
    ],
    projectAccess: [
      'Priority employee volunteer field days (up to 25 staff members)',
      'Quarterly executive briefing with Vision79 Project Directors',
    ],
    reportingBenefits: [
      'Quarterly trans-audited financial and impact dossier',
      'Customized CSR metrics aligned with UN SDGs',
    ],
    badgeColor: 'border-slate-400/50 bg-slate-800/40 text-slate-200',
  },
  {
    id: 'pkg-gold',
    tier: 'Gold Sponsor',
    name: 'Gold Sponsor',
    minContribution: 50000,
    contributionRequirements: 'EC$50,000 - EC$99,999 annual strategic investment',
    recognitionBenefits: [
      'Header/Hero placement on Vision79 Corporate Portal & Main Site',
      'Permanent plaque on field infrastructure facilities',
      'Annual Community Honors Awards VIP presentation seat',
    ],
    marketingBenefits: [
      'Full media kit & co-branded promotional campaign',
      'Executive interview in regional media publications',
    ],
    projectAccess: [
      'Seat on Community Project Steering Advisory Committee',
      'Tailored employee volunteer immersion program (unlimited staff)',
    ],
    reportingBenefits: [
      'Monthly real-time financial expenditure ledger access',
      'Custom impact metric reporting (carbon reduction, literacy, health)',
    ],
    badgeColor: 'border-amber-500/80 bg-amber-950/40 text-amber-300',
  },
  {
    id: 'pkg-platinum',
    tier: 'Platinum Sponsor',
    name: 'Platinum Founding Partner',
    minContribution: 100000,
    contributionRequirements: 'EC$100,000+ multi-year transformational endowment or anchor fund',
    recognitionBenefits: [
      'Title Co-Naming Rights on flagship facilities (e.g., "TechForGood STEM Center")',
      'Top-tier logo placement across all media, signage, vehicles, and press releases',
      'Custom blown-glass Founding Partner Award',
    ],
    marketingBenefits: [
      'Dedicated 3-minute mini-documentary feature film produced by Vision79',
      'Global PR distribution & CSR thought-leadership placement',
    ],
    projectAccess: [
      'Direct co-conception of new community projects from planning phase',
      'Direct access to Board of Directors & Government Liaisons',
    ],
    reportingBenefits: [
      'Dedicated Account Manager & 24/7 audit ledger portal access',
      'Bespoke ESG / CSR Compliance Audit Package for corporate filings',
    ],
    badgeColor: 'border-emerald-500/80 bg-emerald-950/40 text-emerald-300',
  },
];

export const initialCorporateAccounts: CorporateAccount[] = [
  {
    id: 'corp-1',
    companyName: 'TechForGood Global Corporation',
    businessRegistrationNumber: 'REG-2022-8819A',
    contactPerson: 'Amina Mansour',
    email: 'corp@techforgood.io',
    phone: '+1 (758) 450-9900',
    address: 'Suite 400, Innovation Bay, Castries, St. Lucia',
    website: 'https://techforgood.io',
    industry: 'Technology & Telecommunications',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    companyDescription: 'Leading regional technology provider dedicated to expanding digital literacy, STEM education, and clean tech infrastructure across Caribbean communities.',
    verificationStatus: 'Verified',
    tier: 'Platinum Sponsor',
    corporateInterests: ['Education', 'Clean Water', 'Youth Development', 'Digital Literacy'],
    budgetMin: 50000,
    budgetMax: 150000,
    totalContributed: 125000,
    joinedDate: '2024-06-01',
    sponsoredProjects: [
      {
        projectId: 'proj_cleanwater',
        projectName: 'Clean Water Wells for Sunu District',
        amountContributed: 55000,
        date: '2025-03-05',
        impactMetricText: 'Funded solar borehole filtration unit serving 3,500 residents',
        status: 'Active',
      },
      {
        projectId: 'proj_digitallearning',
        projectName: 'FutureTech Digital Literacy Labs in 5 Schools',
        amountContributed: 70000,
        date: '2025-01-15',
        impactMetricText: 'Equipped 30 workstation laptops & fiber connection for 1,200 students',
        status: 'Active',
      },
    ],
    documents: [
      {
        id: 'doc-101',
        title: '501(c)(3) Tax Exemption Certificate - EC$125,000',
        type: 'Tax Certificate 501c3',
        date: '2025-03-10',
        size: '1.2 MB',
        receiptNumber: 'TAX-2025-TFG-001',
      },
      {
        id: 'doc-102',
        title: 'Strategic Partnership MoU - TechForGood & Vision79',
        type: 'MoU Agreement',
        date: '2024-06-01',
        size: '3.4 MB',
      },
      {
        id: 'doc-103',
        title: 'Annual Audited CSR Compliance Dossier 2025',
        type: 'Impact Report',
        date: '2025-12-20',
        size: '4.8 MB',
      },
    ],
    benefits: [
      { key: 'logo_homepage', name: 'Homepage Banner & Top Logo Placement', category: 'Recognition', status: 'Active', details: 'Displayed on primary homepage header & corporate wall' },
      { key: 'co_naming', name: 'STEM Satellite Lab Co-Naming Rights', category: 'Recognition', status: 'Active', details: 'Vieux Fort STEM Satellite Center named in honor of TechForGood' },
      { key: 'volunteer_days', name: 'Dedicated Employee Field Volunteer Days', category: 'Project Access', status: 'Delivered', details: 'Hosted 35 staff members for solar borehole assembly' },
      { key: 'annual_report', name: 'Custom B2B CSR Compliance Audit', category: 'Reporting', status: 'Active', details: 'Generated for 2025 corporate tax disclosures' },
    ],
  },
  {
    id: 'corp-2',
    companyName: 'Apex Renewable Energy Ltd',
    businessRegistrationNumber: 'REG-2023-4412B',
    contactPerson: 'Julian Vance',
    email: 'j.vance@apexenergy.com',
    phone: '+1 (758) 458-1200',
    address: 'Apex Solar Park, Vieux Fort, St. Lucia',
    website: 'https://apexenergy.com',
    industry: 'Energy & Infrastructure',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=300&q=80',
    companyDescription: 'Clean energy pioneer specializing in solar micro-grid installations, sustainable power storage, and rural electrification.',
    verificationStatus: 'Verified',
    tier: 'Gold Sponsor',
    corporateInterests: ['Clean Water', 'Environment', 'Renewable Energy', 'Disaster Relief'],
    budgetMin: 25000,
    budgetMax: 75000,
    totalContributed: 45000,
    joinedDate: '2024-11-12',
    sponsoredProjects: [
      {
        projectId: 'proj_cleanwater',
        projectName: 'Clean Water Wells for Sunu District',
        amountContributed: 45000,
        date: '2024-11-15',
        impactMetricText: 'Supplied 4 high-efficiency solar submersible water pumps',
        status: 'Active',
      },
    ],
    documents: [
      {
        id: 'doc-201',
        title: 'Tax Receipt - EC$45,000 Clean Energy Grant',
        type: 'Tax Certificate 501c3',
        date: '2024-11-20',
        size: '850 KB',
        receiptNumber: 'TAX-2024-APX-002',
      },
      {
        id: 'doc-202',
        title: 'Solar Water Filtration Technical Impact Audit',
        type: 'Audit Report',
        date: '2025-06-30',
        size: '2.1 MB',
      },
    ],
    benefits: [
      { key: 'field_signage', name: 'Field Equipment Engraved Co-Branding', category: 'Recognition', status: 'Active', details: 'Plaque attached to Soufrière Solar Water Station' },
      { key: 'social_feature', name: 'Social Media Green Energy Feature Series', category: 'Marketing', status: 'Delivered', details: 'Highlighting carbon offsets and 3,500 residents served' },
      { key: 'audit_access', name: 'Quarterly Field Audit Ledger Access', category: 'Reporting', status: 'Active', details: 'Real-time telemetry reports on water pump uptime' },
    ],
  },
  {
    id: 'corp-3',
    companyName: 'Horizon Healthcare Fund',
    businessRegistrationNumber: 'REG-2021-1102C',
    contactPerson: 'Dr. Evelyn St. Rose',
    email: 'contact@horizonhealth.org',
    phone: '+1 (758) 452-3344',
    address: 'Health Tower, Rodney Bay, St. Lucia',
    website: 'https://horizonhealth.org',
    industry: 'Healthcare & Life Sciences',
    logo: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=300&q=80',
    companyDescription: 'Regional health foundation investing in rural medical equipment, maternal wellness clinics, and preventive health screenings.',
    verificationStatus: 'Verified',
    tier: 'Silver Sponsor',
    corporateInterests: ['Healthcare', 'Maternal & Child Health', 'Emergency Relief'],
    budgetMin: 10000,
    budgetMax: 30000,
    totalContributed: 25000,
    joinedDate: '2025-01-05',
    sponsoredProjects: [
      {
        projectId: 'proj_maternalclinic',
        projectName: 'Maternal & Child Health Care Mobile Clinic',
        amountContributed: 25000,
        date: '2025-01-10',
        impactMetricText: 'Co-sponsored mobile ultrasound diagnostic unit & maternal screening kits',
        status: 'Active',
      },
    ],
    documents: [
      {
        id: 'doc-301',
        title: 'Tax Receipt - EC$25,000 Health Grant',
        type: 'Tax Certificate 501c3',
        date: '2025-01-12',
        size: '920 KB',
        receiptNumber: 'TAX-2025-HZF-003',
      },
    ],
    benefits: [
      { key: 'mobile_branding', name: 'Mobile Clinic Side-Door Branding', category: 'Recognition', status: 'Active', details: 'Horizon logo displayed on rural mobile medical van' },
      { key: 'annual_cert', name: 'Annual Maternal Health Impact Certificate', category: 'Reporting', status: 'Delivered', details: 'Certified zero maternal deaths in patrol zone' },
    ],
  },
];

export const initialCorporateReports: CorporateReport[] = [
  {
    id: 'rep-1',
    companyId: 'corp-1',
    companyName: 'TechForGood Global Corporation',
    title: '2025-2026 Annual Corporate Social Responsibility (CSR) Impact Dossier',
    reportType: 'CSR Compliance Report',
    period: '2025 - 2026 Annual',
    generatedDate: '2026-08-01',
    totalContribution: 125000,
    projectsCount: 2,
    beneficiariesReached: 4700,
    summary: 'TechForGood Global Corporation contributed EC$125,000 across two flagship community infrastructure initiatives: Soufrière Solar Water Access and Vieux Fort Digital Literacy Labs.',
    executiveKeyTakeaways: [
      '3,500 villagers gained permanent daily access to clean drinking water.',
      '1,200 primary & secondary students acquired hands-on coding work stations.',
      '100% of capital grants verified through trans-audited field ledgers.',
      'EC$125,000 fully tax-exempt under Caribbean Foundation Tax Act section 501(c)(3).',
    ],
  },
  {
    id: 'rep-2',
    companyId: 'corp-2',
    companyName: 'Apex Renewable Energy Ltd',
    title: 'Q2 2026 Clean Energy & Water Infrastructure Sponsorship Report',
    reportType: 'Impact Report',
    period: 'Q2 2026',
    generatedDate: '2026-07-01',
    totalContribution: 45000,
    projectsCount: 1,
    beneficiariesReached: 3500,
    summary: 'Apex Renewable Energy supplied 4 solar submersible pump units, eliminating grid power dependencies and reducing operational costs by 100%.',
    executiveKeyTakeaways: [
      'Zero diesel generator emissions generated during water pumping operations.',
      'Pump telemetry indicates 99.8% operational uptime over 180 consecutive days.',
      'Co-branded site plaque mounted at primary distribution point.',
    ],
  },
];
